import type { ArenaQuiz } from "@/lib/types/arena";

export const sampleArenaQuizzes: ArenaQuiz[] = [
  {
    id: "a1",
    title: "JavaScript Mastery Challenge",
    description: "Test your knowledge on closures, prototypes, async patterns, and modern ES features. Compete with developers worldwide.",
    topic: "JavaScript",
    topicColor: "#E56498",
    tags: ["JavaScript", "ES6", "Async"],
    author: { name: "Alex Chen", username: "alexchen", verified: true },
    enrolled: 1243,
    questions: 25,
    duration: "30 min",
    difficulty: "hard",
    status: "live",
    endsAt: "in 2h 15m",
    isEnrolled: false,
    hasAttempted: false,
    featured: true,
  },
  {
    id: "a2",
    title: "React Hooks Deep Dive",
    description: "useEffect, useMemo, useCallback, custom hooks, and performance optimization.",
    topic: "React",
    topicColor: "#21D3ED",
    tags: ["React", "Hooks"],
    author: { name: "Jordan Lee", username: "jlee", verified: true },
    enrolled: 892,
    questions: 20,
    duration: "25 min",
    difficulty: "medium",
    status: "open-anytime",
    isEnrolled: true,
    hasAttempted: false,
  },
  {
    id: "a3",
    title: "System Design Fundamentals",
    description: "Scalability, load balancing, caching strategies, and database sharding.",
    topic: "System Design",
    topicColor: "#C184FD",
    tags: ["System Design", "Architecture"],
    author: { name: "Sam Patel", username: "spatel" },
    enrolled: 567,
    questions: 15,
    duration: "45 min",
    difficulty: "hard",
    status: "upcoming",
    startsAt: "Apr 20, 6:00 PM",
    isEnrolled: true,
    hasAttempted: false,
  },
  {
    id: "a4",
    title: "Python for Beginners",
    description: "Variables, loops, functions, data structures — perfect for starters.",
    topic: "Python",
    topicColor: "#A3E634",
    tags: ["Python", "Beginner"],
    author: { name: "Taylor Kim", username: "tkim" },
    enrolled: 2156,
    questions: 15,
    duration: "20 min",
    difficulty: "easy",
    status: "open-anytime",
    isEnrolled: false,
    hasAttempted: true,
    userScore: 87,
  },
  {
    id: "a5",
    title: "CSS Grid & Flexbox Challenge",
    description: "Modern layout techniques, responsive design patterns, and common pitfalls.",
    topic: "CSS",
    topicColor: "#FFB32F",
    tags: ["CSS", "Layout"],
    author: { name: "Morgan Davis", username: "mdavis" },
    enrolled: 431,
    questions: 12,
    duration: "15 min",
    difficulty: "medium",
    status: "live",
    endsAt: "in 45m",
    isEnrolled: true,
    hasAttempted: false,
  },
  {
    id: "a6",
    title: "TypeScript Type Gymnastics",
    description: "Advanced types — conditional types, mapped types, utility types, and inference.",
    topic: "TypeScript",
    topicColor: "#21D3ED",
    tags: ["TypeScript", "Advanced"],
    author: { name: "Riley Johnson", username: "rjohnson", verified: true },
    enrolled: 678,
    questions: 18,
    duration: "30 min",
    difficulty: "hard",
    status: "upcoming",
    startsAt: "Apr 18, 3:00 PM",
    isEnrolled: false,
    hasAttempted: false,
  },
  {
    id: "a7",
    title: "Node.js Event Loop",
    description: "Understand the event loop, microtasks, and common async patterns.",
    topic: "Node.js",
    topicColor: "#A3E634",
    tags: ["Node.js", "Backend"],
    author: { name: "Casey Brown", username: "cbrown" },
    enrolled: 312,
    questions: 10,
    duration: "20 min",
    difficulty: "medium",
    status: "ended",
    isEnrolled: true,
    hasAttempted: true,
    userScore: 72,
  },
  {
    id: "a8",
    title: "Database Indexing Secrets",
    description: "B-trees, hash indexes, query optimization, and performance tuning.",
    topic: "Databases",
    topicColor: "#E56498",
    tags: ["Databases", "Performance"],
    author: { name: "Jamie Wilson", username: "jwilson" },
    enrolled: 245,
    questions: 12,
    duration: "25 min",
    difficulty: "hard",
    status: "open-anytime",
    isEnrolled: false,
    hasAttempted: false,
  },
  {
    id: "a9",
    title: "Git Commands Mastery",
    description: "Rebase, cherry-pick, bisect, and advanced git workflows.",
    topic: "Git",
    topicColor: "#C184FD",
    tags: ["Git", "Tools"],
    author: { name: "Avery Martinez", username: "amartinez" },
    enrolled: 1024,
    questions: 15,
    duration: "15 min",
    difficulty: "medium",
    status: "live",
    endsAt: "in 5h 20m",
    isEnrolled: false,
    hasAttempted: false,
  },
];
